{
 "title": "Whoops — Recovery & Sleep Insights",
 "tags": [
  "whoop",
  "recovery",
  "sleep",
  "fitness"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sleep needed baseline",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"sleep_needed_baseline_ms\") from whoop_sleep WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Sleep Debt",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sleep_debt_ms\nFROM whoop_sleep\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "AVG heart rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"avg_heart_rate\") from whoop_cycle WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Strain vs Recovery Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT c.timestamp AS \"time\", c.strain, r.recovery_score FROM whoop_cycle c JOIN whoop_recovery r ON c.id = r.cycle_id WHERE $__timeFilter(c.timestamp) ORDER BY c.timestamp;"
    }
   ]
  },
  {
   "title": "AVG vs MAX Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"avg_heart_rate\" from whoop_cycle WHERE $__timeFilter(timestamp);"
    },
    {
     "rawSql": "SELECT \"timestamp\", \"max_heart_rate\" from whoop_cycle WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Kilojoules",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"kilojoule\" from whoop_cycle WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  { "title": "Sleep", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "REM Sleep Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \"total_rem_sleep_ms\", \"timestamp\" FROM whoop_sleep WHERE $__timeFilter(timestamp) GROUP BY \"total_rem_sleep_ms\", \"timestamp\" "
    }
   ]
  },
  {
   "title": "Needed vs Debt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"sleep_debt_ms\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    },
    {
     "rawSql": "SELECT \"timestamp\", \"add_sleep_from_strain_ms\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "In bed vs Awake",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"total_in_bed_ms\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    },
    {
     "rawSql": "SELECT \"timestamp\", \"total_awake_ms\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Sleep Duration vs Performance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"total_in_bed_ms\", \"performance_perc\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Cycle vs Disturbance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"sleep_cycle_count\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    },
    {
     "rawSql": "SELECT \"timestamp\", \"disturbance_count\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"efficiency_perc\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Consistency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"consistency_perc\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Respiratory Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"respiratory_rate\" FROM whoop_sleep WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  { "title": "Recovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "HRV vs Resting Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"hrv_rmssd_ms\" from whoop_recovery WHERE $__timeFilter(timestamp); "
    },
    {
     "rawSql": "SELECT \"timestamp\", \"resting_heart_rate\" from whoop_recovery WHERE $__timeFilter(timestamp); "
    }
   ]
  },
  {
   "title": "Skin Temperature vs Recovery Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"skin_temp_celsius\" FROM whoop_recovery WHERE $__timeFilter(timestamp);"
    },
    {
     "rawSql": "SELECT \"timestamp\", \"recovery_score\" FROM whoop_recovery WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "SpO2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", \"spo2_perc\" FROM whoop_recovery WHERE $__timeFilter(timestamp);"
    }
   ]
  },
  { "title": "Workout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Workout count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS workout_count\nFROM whoop_workout \nWHERE $__timeFilter(start);"
    }
   ]
  },
  {
   "title": "Strain",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n\"timestamp\", \"strain\", \"kilojoule\"\nFROM whoop_workout\nWHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "AVG vs MAX heart rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n\"timestamp\", \"avg_heart_rate\", \"max_heart_rate\"\nFROM whoop_workout\nWHERE $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Zone split ",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(zone_zero_milli) as zero, SUM(zone_one_milli) as one, SUM(zone_two_milli) as two, SUM(zone_three_milli) as three, SUM(zone_four_milli) as four, SUM(zone_five_milli) as five\nFROM whoop_workout\nWHERE $__timeFilter(timestamp);\n \n"
    }
   ]
  },
  {
   "title": "Zone split ",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, SUM(zone_zero_milli) as zero, SUM(zone_one_milli) as one, SUM(zone_two_milli) as two, SUM(zone_three_milli) as three, SUM(zone_four_milli) as four, SUM(zone_five_milli) as five\nFROM whoop_workout\nWHERE $__timeFilter(timestamp) \nGROUP BY timestamp\nORDER BY timestamp ASC;\n"
    }
   ]
  }
 ]
}