apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enshrouded-server-restored
  namespace: enshrouded
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi
