apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enshrouded-server
  namespace: enshrouded
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
