apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: enshrouded-server
  namespace: enshrouded
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: enshrouded-server
  data:
    - secretKey: ENSHROUDED_ROLE_0_PASSWORD
      remoteRef:
        key: apps
        property: ENSHROUDED_ROLE_0_PASSWORD
