apiVersion: v1
kind: Service
metadata:
  name: enshrouded-server
  namespace: enshrouded
  annotations:
    metallb.io/address-pool: enshrouded-server
spec:
  selector:
    app.kubernetes.io/name: enshrouded-server
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 15637
      targetPort: 15637
