apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wyrm-creds
  namespace: wyrm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: wyrm-creds
  data:
    - secretKey: username
      remoteRef:
        key: apps
        property: WYRM_DB_USERNAME
    - secretKey: password
      remoteRef:
        key: apps
        property: WYRM_DB_PASSWORD
    - secretKey: WYRM_DATABASE_CONNECTION
      remoteRef:
        key: apps
        property: WYRM_DATABASE_CONNECTION
    - secretKey: WYRM_API_KEY
      remoteRef:
        key: apps
        property: WYRM_API_KEY
