apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: home-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: "nfs-storage"
