apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: plex-ns
spec:
  selector:
    app: radarr
  ports:
  - protocol: TCP
    port: 7878
    targetPort: 7878
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: plex-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "4000"
        - name: TZ
          value: "Canada/Pacific"
        volumeMounts:
        - name: media
          mountPath: /config
          subPath: config/radarr
        - name: media
          mountPath: /media/downloads
          subPath: downloads
        - name: media
          mountPath: /media/movies
          subPath: movies
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: plex-media-pvc