apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-pictrs
  namespace: lemmy
spec:
  podSelector:
    matchLabels:
      app: pictrs
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.22.10.10/32
      ports:
        - protocol: TCP
          port: 2049
        - protocol: UDP
          port: 2049
