apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner-pihole
  labels:
    app: nfs-provisioner-pihole
  namespace: home-apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-provisioner-pihole
  template:
    metadata:
      labels:
        app: nfs-provisioner-pihole
    spec:
      serviceAccountName: nfs-provisioner
      containers:
        - name: nfs-provisioner-pihole
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: server01.kryoseu.com
            - name: NFS_PATH
              value: /tank/pihole-share
      volumes:
        - name: nfs-client-root
          nfs:
            server: server01.kryoseu.com
            path: /tank/pihole-share
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  namespace: home-apps
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /tank/pihole-share
    server: server01.kryoseu.com