apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whoops-creds
  namespace: whoops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: whoops-creds
  data:
    - secretKey: username
      remoteRef:
        key: whoops-creds
        property: WHOOPS_DB_USERNAME
    - secretKey: password
      remoteRef:
        key: whoops-creds
        property: WHOOPS_DB_PASSWORD
    - secretKey: SQLALCHEMY_DATABASE_URI
      remoteRef:
        key: whoops-creds
        property: SQLALCHEMY_DATABASE_URI
    - secretKey: CLIENT_ID
      remoteRef:
        key: whoops-creds
        property: WHOOP_CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: whoops-creds
        property: WHOOP_CLIENT_SECRET
