apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lemmy-postgres
  # annotations:
  #   cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  description: Postgres cluster for the Lemmy application
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  instances: 3

  storage:
    size: 10Gi

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: "s3://kryoseu-lemmy/postgres"
        serverName: "lemmy-postgres"
        s3Credentials:
          accessKeyId:
            name: aws-creds-envs
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds-envs
            key: ACCESS_SECRET_KEY

  backup:
    barmanObjectStore:
      destinationPath: "s3://kryoseu-lemmy/postgres"
      s3Credentials:
        accessKeyId:
          name: aws-creds-envs
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds-envs
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d

  # bootstrap:
  #   recovery:
  #     source: clusterBackup
  #     database: lemmy
  #     owner: lemmy
  #     secret:
  #       name: lemmy-creds

  bootstrap:
    initdb:
      database: lemmy
      owner: lemmy
      secret:
        name: lemmy-creds
