apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: wireguard
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - wireguard.kryoseu.com
    secretName: wireguard-tls
  rules:
  - host: wireguard.kryoseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wireguard-vpn-metrics-svc
            port:
              number: 9586 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: home-apps
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - otarios.kryoseu.com
    secretName: rocketchat-tls
  rules:
  - host: otarios.kryoseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocketchat-server
            port:
              number: 3000 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: plex-ns
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - radarr.kryoseu.com
    - sonarr.kryoseu.com
    - deluge.kryoseu.com
    - prowlarr.kryoseu.com
    secretName: plex-arr-tls
  rules:
  - host: sonarr.kryoseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989 
  - host: radarr.kryoseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 7878 
  - host: deluge.kryoseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deluge
            port:
              number: 8112 
  - host: prowlarr.kryoseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 9696 