kubeControllerManager:
  service:
    selector:
      k8s-app: kube-controller-manager
kubeScheduler:
  service:
    selector:
      k8s-app: kube-scheduler
      
prometheus:
  prometheusSpec:
    # Watch only namespaces with this label
    podMonitorNamespaceSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring

    # But allow ServiceMonitors from any namespace
    serviceMonitorNamespaceSelector: {}

    # Discovery settings
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

    ignoreNamespaceSelectors: true

grafana:
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 4Gi
