kubeControllerManager:
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    selfMonitor: true
    https: 'true'
    insecureSkipVerify: 'true'
    
kubeScheduler:
  service:
    port: 10259
    targetPort: 10259
  serviceMonitor:
    selfMonitor: true
    https: 'true'
    insecureSkipVerify: 'true'
    
kubeProxy:
  service:
    port: 10249
    targetPort: 10249
  serviceMonitor:
    selfMonitor: true
    scheme: 'http'

kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
  serviceMonitor:
    selfMonitor: true
    scheme: 'http'
    
prometheus:
  prometheusSpec:
    # Watch only namespaces with this label
    podMonitorNamespaceSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring

    # But allow ServiceMonitors from any namespace
    serviceMonitorNamespaceSelector: {}

    # Discovery settings
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

    ignoreNamespaceSelectors: true

grafana:
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring:3100

  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 4Gi
