apiVersion: v1
kind: Service
metadata:
  name: excalidraw
  namespace: home-apps
  labels:
    app.kubernetes.io/name: excalidraw
    app.kubernetes.io/instance: excalidraw
spec:
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: excalidraw
    app.kubernetes.io/instance: excalidraw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: home-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: excalidraw
      app.kubernetes.io/instance: excalidraw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: excalidraw
        app.kubernetes.io/instance: excalidraw
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: excalidraw
          image: "excalidraw/excalidraw@sha256:0295d7a1614afac68e6c602da6d7168c1505c9926eefcee0fcce9c5eadd42052"
          securityContext:
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
              drop:
                - ALL
            privileged: false
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /var/run
              name: nginx-run
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
