apiVersion: v1
kind: Service
metadata:
  name: excalidraw
  namespace: home-apps
  labels:
    app.kubernetes.io/name: excalidraw
    app.kubernetes.io/instance: excalidraw
spec:
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: excalidraw
    app.kubernetes.io/instance: excalidraw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
  namespace: home-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: excalidraw
      app.kubernetes.io/instance: excalidraw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: excalidraw
        app.kubernetes.io/instance: excalidraw
    spec:
      containers:
        - name: excalidraw
          image: "excalidraw/excalidraw:latest"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
