apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - wyrm.yaml
  - paperless-ngx.yaml
  - deluge-gluetun.yaml
  - enshrouded.yaml
  - lemmy.yaml
  - plex.yaml
  - renovate.yaml
  - whoops.yaml
  - immich-db.yaml
