apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-env
  namespace: home-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: renovate-env
    template:
      engineVersion: v2
      data:
        RENOVATE_HOST_RULES: '[{"matchHost":"ghcr.io","hostType":"docker","username":"kryoseu","password":"{{ .RENOVATE_TOKEN }}"}]'
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: apps
        property: RENOVATE_TOKEN
