apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner-pihole
  labels:
    app: nfs-provisioner-pihole
  namespace: home-apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-provisioner-pihole
  template:
    metadata:
      labels:
        app: nfs-provisioner-pihole
    spec:
      serviceAccountName: nfs-provisioner-pihole
      containers:
        - name: nfs-provisioner-pihole
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: <NFS_SERVER_IP>
            - name: NFS_PATH
              value: /tank/pihole-share
      volumes:
        - name: nfs-client-root
          nfs:
            server: <NFS_SERVER_IP>
            path: /tank/pihole-share
