apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-claim-token
  namespace: plex-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: plex-claim-token
  data:
    - secretKey: PLEX_CLAIM
      remoteRef:
        key: plex-claim
