apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - service_acc.yaml
  - secret.yaml
  - clusterrole.yaml
  - service.yaml
  - deployment.yaml
