apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: wyrm-postgres
  namespace: wyrm
spec:
  immediate: true
  schedule: "0 0 7 * * *"
  backupOwnerReference: cluster
  cluster:
    name: wyrm-postgres
