apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-kv-store
  annotations:
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    aws:
      service: SecretsManager
      role: arn:aws:iam::333108038516:role/homelab
      region: us-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-access-key
    