apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: production-pihole
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
  name: pihole-dhcp
  namespace: home-apps
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: <SERVER_IP>
  ports:
  - name: client-dhcp
    port: 67
    protocol: UDP
    targetPort: client-dhcp
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer