apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: production-pihole
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
  name: pihole-dns-tcp
  namespace: home-apps
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: <PIHOLE_IP>
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer