apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: production-pihole
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
  name: pihole-web
  namespace: home-apps
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: <PIHOLE_IP>
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: pihole-http
  - name: pihole-ssl
    port: 443
    protocol: TCP
    targetPort: pihole-ssl
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer