apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: home-apps
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - image: renovate/renovate:40.0.4
              name: renovate-bot
              args:
                - kryoseu/homelab
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                runAsUser: 1000
                runAsGroup: 1000
              envFrom:
                - secretRef:
                    name: renovate-env
                - configMapRef:
                    name: renovate-configmap
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}