apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: home-apps
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - image: renovate/renovate:41.43.0
              name: renovate-bot
              args:
                - kryoseu/homelab
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                runAsUser: 1000
                runAsGroup: 1000
              envFrom:
                - secretRef:
                    name: renovate-env
                - configMapRef:
                    name: renovate-configmap
          restartPolicy: Never

