apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-env
  namespace: home-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: renovate-env
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate-token
