apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deluge-gluetun-envs
  namespace: plex-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: deluge-gluetun-envs
  data:
    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: apps
        property: GLUETUN_SERVER_COUNTRIES
    - secretKey: SERVER_CITIES
      remoteRef:
        key: apps
        property: GLUETUN_SERVER_CITIES
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: apps
        property: WIREGUARD_PRIVATE_KEY
