apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-apps.yaml
  - wyrm.yaml
  - paperless-ngx.yaml
  - plex-ns.yaml
  - enshrouded.yaml
  - homepage.yaml
  - lemmy.yaml
  - whoops.yaml
