apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-deluge
  namespace: plex-ns
spec:
  podSelector:
    matchLabels:
      app: deluge-vpn
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8112
    - from:
        - podSelector:
            matchLabels:
              app: radarr
        - podSelector:
            matchLabels:
              app: sonarr
      ports:
        - protocol: TCP
          port: 8112
