apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-radarr
  namespace: plex-ns
spec:
  podSelector:
    matchLabels:
      app: radarr
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 7878

    - from:
        - podSelector:
            matchLabels:
              app: prowlarr
      ports:
        - protocol: TCP
          port: 7878
