apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
  namespace: portainer
  labels:
    app: portainer
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: server01.kryoseu.com
    path: /tank/portainer-share