apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: production-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - postgres-production
    - plex-production
    - apps-ext-production
    - pihole-production
