apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wireguard-metrics
  namespace: wireguard
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http 
  selector:
    matchLabels:
      app: wireguard
      instance: wireguard-vpn
  namespaceSelector:
    matchNames:
    - wireguard
