apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-lemmy
  namespace: lemmy
spec:
  podSelector:
    matchLabels:
      app: lemmy
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8536
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 10002
    - from:
        - podSelector:
            matchLabels:
              app: lemmy-ui
      ports:
        - protocol: TCP
          port: 8536
