# Manually creating a PV here to avoid having to create a separate NFS provisioner
# for the encrypted ZFS dataset within /tank/home-apps
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-encrypted
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: server01.kryoseu.com
    path: /tank/home-apps/encrypted/immich-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-encrypted
  namespace: home-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-storage
  volumeName: immich-library-encrypted
