apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: home-apps
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - otarios.kryoseu.com
    secretName: wildcard-tls
  rules:
  - host: otarios.kryoseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocketchat-server
            port:
              number: 3000 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: plex-ns
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - plex.kryoseu.com
    - radarr.kryoseu.com
    secretName: wildcard-tls
  rules:
  - host: plex.kryoseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex-server
            port:
              number: 32400 
  - host: radarr.kryoseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 7878 


