apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  # annotations:
  #   cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  description: Postgres cluster for the immich app application
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.2@sha256:649da2df5f079dd1f214e3a877cafd0208eff3779e9c60d14d243fbca5e11c97
  instances: 3

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  inheritedMetadata:
    labels:
      app: immich-database
      policy-type: "database"

  storage:
    size: 5Gi

  managed:
    roles:
      - name: immich
        superuser: true
        login: true

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: "s3://kryoseu-immich-library/postgres"
        serverName: "immich-postgres"
        s3Credentials:
          accessKeyId:
            name: aws-creds-envs
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds-envs
            key: ACCESS_SECRET_KEY

  backup:
    barmanObjectStore:
      destinationPath: "s3://kryoseu-immich-library/postgres"
      s3Credentials:
        accessKeyId:
          name: aws-creds-envs
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds-envs
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d

  bootstrap:
    recovery:
      source: clusterBackup
      database: immich
      owner: immich
      secret:
        name: immich-db-creds
