apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-db-user
  namespace: home-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: immich-db-user
  data:
    - secretKey: IMMICH-DB-USER
      remoteRef:
        key: immich-db-user
