apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-db-creds
  namespace: home-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: immich-db-creds
  data:
    - secretKey: username
      remoteRef:
        key: immich-db-username
    - secretKey: password
      remoteRef:
        key: immich-db-password
