apiVersion: v1
kind: Service
metadata:
  name: lemmy-ui
spec:
  selector:
    app: lemmy-ui
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemmy-ui
  namespace: lemmy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lemmy-ui
  template:
    metadata:
      labels:
        app: lemmy-ui
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: lemmy-ui
          image: dessalines/lemmy-ui:0.19.17
          ports:
            - containerPort: 1234
              protocol: TCP
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: LEMMY_UI_LEMMY_INTERNAL_HOST
              value: "lemmy:8536"
            - name: LEMMY_UI_LEMMY_EXTERNAL_HOST
              value: "lemmy.bunga.kryoseu.com"
            - name: LEMMY_UI_HTTPS
              value: "true"
          readinessProbe:
            httpGet:
              path: /
              port: 1234
            initialDelaySeconds: 15
