apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lemmy-creds
  namespace: lemmy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: lemmy-creds
  data:
    - secretKey: username
      remoteRef:
        key: apps
        property: LEMMY_DB_USERNAME
    - secretKey: password
      remoteRef:
        key: apps
        property: LEMMY_DB_PASSWORD
    - secretKey: pictrs-api-key
      remoteRef:
        key: apps
        property: PICTRS_SERVER_API_KEY
